const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict'),{test}=require('node:test');
const sourcePath=process.env.ATTENDANCE_PHOTO_SOURCE || [path.resolve(__dirname,'../codeabsensi.txt'),path.resolve(__dirname,'../../codeabsensi.txt')].find(p=>fs.existsSync(p));
const source=sourcePath?fs.readFileSync(sourcePath,'utf8'):'';
const backendTest=(name,fn)=>test(name,{skip:!source},fn);
function harness(role='admin',name='Test'){
 const requests=[];const rows=[{id_absen:'a',nama_pegawai:'Test',waktu_absen:'2026-09-17T08:00:00+08:00',tipe_absen:'Masuk',bukti_foto:'https://example.test/in',lokasi_maps:'https://www.google.com/maps?q=-3.97,122.51'},{id_absen:'b',nama_pegawai:'Test',waktu_absen:'2026-09-17T12:00:00+08:00',tipe_absen:'Keluar',bukti_foto:'https://example.test/out',lokasi_maps:'-'},{id_absen:'c',nama_pegawai:'Other',waktu_absen:'2026-09-17T08:00:00+08:00',tipe_absen:'Masuk',bukti_foto:'https://example.test/other',lokasi_maps:'https://www.google.com/maps?q=-4,123'}];
 class FixedDate extends Date{constructor(...args){super(...(args.length?args:['2026-09-17T12:30:00+08:00']));}}
 const c=vm.createContext({Date:FixedDate,console,PropertiesService:{getScriptProperties:()=>({getProperty:()=> 'test-only'})},ContentService:{MimeType:{JSON:'json'},createTextOutput:text=>({setMimeType:()=>JSON.parse(text)})},Utilities:{formatDate(d,tz,format){const iso=new Date(new Date(d).getTime()+8*3600000).toISOString();return format==='HH:mm'?iso.slice(11,16):format==='dd MMM yyyy'?'17 Sep 2026':iso.slice(0,10);}}});
 vm.runInContext(source,c);c.verifikasiSessionToken_=()=> 'test';c.callSupabase_=(url)=>{requests.push(url);if(url.includes('/users?'))return [{username:'test',nama_asli:name,role,hak_akses_cabang:'Kendari'}];if(url.includes('/pengajuan_cuti?'))return [];if(url.includes('/absensi?')){assert.ok(url.includes('bukti_foto'));return url.includes('nama_pegawai=eq.')?rows.filter(r=>r.nama_pegawai===name):rows;}throw Error('unexpected request');};
 return {requests,run:action=>c.doPost({postData:{contents:JSON.stringify({action,periode:'2026-09',apiKey:vm.runInContext('API_KEY',c),user:{}})}})};
}
backendTest('Payroll receives photo and location columns without shifting existing columns',()=>{const h=harness();const r=h.run('getAbsen');assert.equal(r.status,'sukses');assert.deepEqual(Array.from(r.data[0]),['Waktu Absen','Nama Pegawai','Tipe Absen','Keterangan','Status Disiplin','Kembali Bekerja','Bukti Foto','Lokasi Maps']);assert.equal(r.data[1][6],'https://example.test/in');assert.equal(r.data[1][7],'https://www.google.com/maps?q=-3.97,122.51');assert.ok(h.requests.some(url=>url.includes('lokasi_maps')));});
backendTest('Review groups all photos by employee; Kendari sales read only their own slip',()=>{const manager=harness().run('getTinjauanAbsen');assert.equal(manager.status,'sukses');assert.equal(manager.data.length,2);const testUser=manager.data.find(r=>r.nama==='Test');assert.deepEqual(Array.from(testUser.foto,r=>r.url),['https://example.test/in','https://example.test/out']);const h=harness('sales');assert.equal(h.run('getTinjauanAbsen').status,'gagal');const slip=h.run('getAbsen');assert.equal(slip.status,'sukses');assert.equal(slip.data.length,3);assert.ok(h.requests.some(url=>url.includes('/absensi?')&&url.includes('nama_pegawai=eq.Test')));assert.ok(slip.data.slice(1).every(row=>!String(row).includes('https://www.google.com/maps?q=-4,123')));});
