const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict'),{test}=require('node:test');
const source=fs.readFileSync(path.join(__dirname,'../maintenance/kpi-lobby-bridge.js'),'utf8');
test('SLA page embeds the tested bridge and gated KPI button',()=>{const html=fs.readFileSync(path.join(__dirname,'../index.html'),'utf8').replace(/\r\n/g,'\n');assert.ok(html.includes(source.replace(/\r\n/g,'\n').trim()));assert.ok(html.includes("if (menu === 'kpi') return penggunaBolehMengaksesKpi_(user);"));assert.equal((html.match(/id="btn-lobby-kpi"/g)||[]).length,1);});
function harness(role='direktur',branch='Semua',login=''){const listeners=new Map(),calls=[],messages=[],ui={button:{disabled:false},status:{innerText:''}};let openedUrl,timer;const tab={closed:false,postMessage:(value,origin)=>messages.push({value,origin}),close(){this.closed=true;}};const c=vm.createContext({console,Uint8Array,AbortController,crypto:{getRandomValues:arr=>arr.fill(5)},penggunaAktif:{Role:role,Hak_Akses_Cabang:branch,Username_Login:login,SessionToken:'sla-jwt'},punyaAksesLobby:()=>true,showToast:()=>{},document:{getElementById:id=>id==='btn-lobby-kpi'?ui.button:ui.status},window:{open:url=>(openedUrl=url,tab),addEventListener:(name,fn)=>listeners.set(name,fn),removeEventListener:name=>listeners.delete(name)},setTimeout:fn=>(timer=fn,1),clearTimeout:()=>{},pastikanTokenSupabaseAktif_:async()=>{},fetch:async(url,init)=>{calls.push({url,body:JSON.parse(init.body)});return {ok:true,json:async()=>({ok:true,token:'only-kpi-token'})};}});vm.runInContext(source,c);return{c,tab,calls,messages,ui,listeners,opened:()=>openedUrl,expire:()=>timer()};}
for(const [role,branch,allowed]of [['direktur','Semua',true],['manager','Semua',true],['admin','Kendari',true],['admin','Semua',true],['admin','Raha',true],['admin_raha','Raha',true],['teknisi','Kendari',false],['sales','Kendari',false],['admin','Unknown',false]])test(`Lobby access ${role}/${branch}`,()=>assert.equal(harness(role,branch).c.penggunaBolehMengaksesKpi_(),allowed));
test('Parent transfers the active SLA session only to the expected KPI child and never puts a token in the URL',async()=>{const h=harness(),result=h.c.bukaAplikasiKpi();await new Promise(resolve=>setImmediate(resolve));assert.ok(!h.opened().includes('jwt'));const nonce=new URL(h.opened()).hash.slice('#sla-handoff='.length),listener=h.listeners.get('message'),ready={origin:'https://alfacomapp.github.io',source:h.tab,data:{type:'kpi:sla-ready',nonce}};listener({...ready,origin:'https://evil.test'});listener({...ready,source:{}});listener({...ready,data:{...ready.data,nonce:'wrong'}});assert.equal(h.messages.length,0);listener(ready);assert.equal(h.messages[0].value.token,'sla-jwt');assert.equal(h.messages[0].origin,'https://alfacomapp.github.io');assert.equal(h.calls.length,0,'handoff must use the current Supabase session directly');listener({...ready,data:{type:'kpi:sla-accepted',nonce}});await result;assert.equal(h.listeners.size,0);assert.equal(h.ui.button.disabled,false);assert.equal(h.tab.closed,false);});
test('Timeout closes incomplete handoff and restores lobby controls',async()=>{const h=harness(),result=h.c.bukaAplikasiKpi();await new Promise(resolve=>setImmediate(resolve));h.expire();await result;assert.equal(h.tab.closed,true);assert.equal(h.listeners.size,0);assert.equal(h.ui.button.disabled,false);});

for(const [role,branch,login,allowed] of [['teknisi','Kendari','alif',true],['teknisi','Raha','alif',true],['teknisi','Raha','wawan',false],['teknisi','Kendari','alif2',false],['sales','Kendari','alif',false],['sales','Kendari','juna',true]]) test('KPI exception '+role+'/'+branch+'/'+login,()=>assert.equal(harness(role,branch,login).c.penggunaBolehMengaksesKpi_(),allowed));
