const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict'),{test}=require('node:test');
const root=path.resolve(__dirname,'..'),helper=fs.readFileSync(path.join(root,'maintenance/prospect-ticket-sync.js'),'utf8');
const ticket={id_tiket:'TKT-148',klien_lokasi:'EKING',no_wa_klien:'6285345640323',sales:'Ummu Abdillah',cabang:'Kendari',waktu_lapor:'2026-09-17T12:27:42+08:00',status:'Selesai'};
const prospect={id_prospek:'PRP-057',nama_calon_customer:'User printer',no_wa:ticket.no_wa_klien,sales_penanggung_jawab:ticket.sales,cabang:'Kendari',tanggal_input:'2026-09-12T08:00:00+08:00',status_prospek:'Tahap Penawaran'};
function harness(rows=[{...prospect}],fresh={...ticket},options={}){const patches=[],notifs=[],queries=[];const c=vm.createContext({console,Map,Set,Date,cabangAktif:'Kendari',globalProspek:[{'ID Prospek':'PRP-057','Status Prospek':'Tahap Penawaran'}],normalisasiCabang:v=>String(v).trim().toLowerCase()==='raha'?'Raha':String(v).trim().toLowerCase()==='kendari'?'Kendari':'',normalisasiWASementara_:v=>String(v||'').replace(/\D/g,'').replace(/^0/,'62'),endpointFilterSupabase_:(t,k,v)=>t+'?'+k+'=eq.'+encodeURIComponent(v),pastikanHasilMutasiSupabase_:r=>assert.ok(Array.isArray(r)&&r.length),kirimNotifWAInternal:async(...args)=>(notifs.push(args),{terkirim:1}),callSupabase:async(endpoint,method,payload)=>{queries.push(endpoint);if(method==='PATCH'){patches.push({endpoint,payload});return options.race?[]:[{id_prospek:'PRP-057',...payload}];}return endpoint.startsWith('tiket?')?[fresh]:rows;}});vm.runInContext(helper,c);return {c,patches,notifs,queries,run:()=>c.sinkronkanStatusProspekDariTiket_('On Progress','wrong','wrong',{'ID Tiket':fresh.id_tiket,Cabang:fresh.cabang})};}
test('Different customer label follows fresh stored ticket through matching WA/sales/branch',async()=>{const h=harness(),r=await h.run();assert.equal(r.diperbarui,1);assert.equal(h.patches[0].payload.status_prospek,'Closing / Deal');assert.ok(h.queries.every(q=>q.includes('cabang=eq.Kendari')));assert.ok(h.patches[0].endpoint.includes('status_prospek=eq.Tahap%20Penawaran'));assert.equal(h.notifs.length,1);assert.equal(h.c.globalProspek[0]['Status Prospek'],'Closing / Deal');});
for(const status of ['Tahap Penawaran','Kunjungan Toko','On Progress','Pending','Proses Servis'])test(`Nonfinal state ${status} can follow completion`,async()=>assert.equal((await harness([{...prospect,status_prospek:status}]).run()).diperbarui,1));
for(const status of ['Closing / Deal','Batal','Tanpa Keterangan',''])test(`Final/manual state ${status} is preserved`,async()=>{const h=harness([{...prospect,status_prospek:status}]);assert.equal((await h.run()).diperbarui,0);assert.equal(h.notifs.length,0);});
for(const changes of [{cabang:'Raha'},{no_wa:'6281111111111'},{sales_penanggung_jawab:'Another Sales'},{tanggal_input:'2026-09-18T08:00:00+08:00'},{tanggal_input:'invalid'}])test(`Unrelated prospect is excluded: ${JSON.stringify(changes)}`,async()=>{const h=harness([{...prospect,...changes}]);assert.equal((await h.run()).diperbarui,0);});
test('Ambiguous shared number does not close either prospect',async()=>{const h=harness([{...prospect},{...prospect,id_prospek:'PRP-058',nama_calon_customer:'Another customer'}]);const r=await h.run();assert.equal(r.ambigu,true);assert.equal(r.diperbarui,0);assert.equal(h.notifs.length,0);});
test('A unique exact name resolves shared-number ambiguity',async()=>{const h=harness([{...prospect,nama_calon_customer:'EKING'},{...prospect,id_prospek:'PRP-058',nama_calon_customer:'Another customer'}]);assert.equal((await h.run()).diperbarui,1);});
test('Manual concurrent change is preserved and produces no duplicate notification',async()=>{const h=harness(undefined,undefined,{race:true});assert.equal((await h.run()).diperbarui,0);assert.equal(h.notifs.length,0);});
test('Status already matching ticket does not write or notify',async()=>{const h=harness([{...prospect,status_prospek:'Pending'}],{...ticket,status:'Pending'});assert.equal((await h.run()).diperbarui,0);assert.equal(h.patches.length,0);assert.equal(h.notifs.length,0);});
test('Ticket transitions retain existing mapping',()=>{const h=harness();for(const [from,to]of [['On Progress','On Progress'],['Pending','Pending'],['Selesai','Closing / Deal'],['Closed','Closing / Deal'],['Cancel','Batal'],['Menunggu',''],['Outsource','']])assert.equal(h.c.statusProspekDariStatusTiket_(from),to);});
test('Production embeds tested helper, supplies ticket identity, and reads correct WA field',()=>{const html=fs.readFileSync(path.join(root,'index.html'),'utf8').replace(/\r\n/g,'\n');assert.ok(html.includes(helper.replace(/\r\n/g,'\n').trim()));assert.ok(html.includes("'ID Tiket': idTiket, Cabang: cabangTiket"));assert.ok(!html.includes("tiketLama['WA Klien']"));});
